# Generated by Django 4.1 on 2024-02-24 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("answerquestion", "0002_series_useranswer"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="pub_date",),
        migrations.AddField(
            model_name="question",
            name="series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="answerquestion.series",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="answerquestion.question",
            ),
        ),
    ]
