# Generated by Django 4.2.10 on 2024-02-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_game_start', models.DateTimeField(blank=True, null=True)),
                ('verified_locations_count', models.IntegerField(default=0)),
            ],
        ),
    ]
