# Generated by Django 4.2.10 on 2024-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0002_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checker',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
