# Generated by Django 4.1 on 2024-03-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navi", "0003_alter_checker_latitude_alter_checker_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="checker",
            name="overview",
            field=models.TextField(default="Beautiful spot"),
        ),
        migrations.AddField(
            model_name="checker",
            name="picture",
            field=models.TextField(default="navi/static/images/Journey-amico.png"),
        ),
        migrations.AddField(
            model_name="checker",
            name="tag",
            field=models.CharField(default="question", max_length=255),
        ),
        migrations.AlterField(
            model_name="checker",
            name="location_name",
            field=models.TextField(default="Beautiful name"),
        ),
    ]
