# Generated by Django 4.2.10 on 2024-03-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0003_alter_checker_latitude_alter_checker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='overview',
            field=models.TextField(default='Beautiful spot'),
        ),
        migrations.AddField(
            model_name='checker',
            name='picture',
            field=models.ImageField(default='python manage.py makemigrations', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='checker',
            name='tag',
            field=models.CharField(default='question', max_length=255),
        ),
    ]
