# Generated by Django 4.2.10 on 2024-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0005_alter_checker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='location_name',
            field=models.TextField(default='Beautiful name'),
        ),
    ]
