# Generated by Django 5.1.dev20240127105402 on 2024-03-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0004_checker_overview_checker_picture_checker_tag_and_more'),
        ('navi', '0007_alter_checker_picture'),
    ]

    operations = [
    ]
