# Generated by Django 5.1.dev20240127105402 on 2024-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0008_merge_20240319_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='picture',
            field=models.TextField(default='/static/images/Journey-amico.png'),
        ),
    ]
