# Generated by Django 5.0.2 on 2024-02-26 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_data", models.DateTimeField()),
            ],
        ),
    ]
