# Generated by Django 5.0.2 on 2024-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="announcement_images/"
            ),
        ),
    ]
