# Generated by Django 4.1 on 2024-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_announcement_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="announcement/images/"
            ),
        ),
    ]
