# Generated by Django 5.0.3 on 2024-03-17 20:08

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=pictures.models.custom_upload_path),
        ),
    ]
