# Generated by Django 4.1 on 2024-02-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usersinformation", "0003_playerprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(model_name="playerprofile", name="user",),
    ]
