# Generated by Django 4.1 on 2024-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0002_achievement_icon_alter_achievement_name"),
        ("usersinformation", "0004_remove_playerprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="achievements",
            field=models.ManyToManyField(
                blank=True, related_name="pk", to="achievement.achievement"
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="displayed_achievements",
            field=models.ManyToManyField(
                blank=True,
                related_name="displayed_by_users",
                to="achievement.achievement",
            ),
        ),
    ]
