# Generated by Django 4.1 on 2024-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0002_achievement_icon_alter_achievement_name"),
        ("usersinformation", "0005_playerprofile_achievements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="achievements",
            field=models.ManyToManyField(
                blank=True, related_name="user", to="achievement.achievement"
            ),
        ),
    ]
