# Generated by Django 4.1 on 2024-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerquestion", "0004_question_score"),
        ("usersinformation", "0007_playerprofile_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="completed_series",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="answerquestion.series"
            ),
        ),
    ]
