# Generated by Django 4.1 on 2024-02-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_user_email"),
        ("usersinformation", "0010_alter_playerprofile_completed_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="web.user"
            ),
        ),
    ]
