# Generated by Django 4.1 on 2024-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersinformation", "0012_alter_playerprofile_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="playerprofile", name="user",),
        migrations.AddField(
            model_name="playerprofile",
            name="last_game_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="verified_locations_count",
            field=models.IntegerField(default=0),
        ),
    ]
