# Generated by Django 4.1 on 2024-02-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usersinformation", "0013_remove_playerprofile_user_and_more"),
        ("web", "0002_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="player_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="usersinformation.playerprofile",
            ),
        ),
    ]
