# Generated by Django 4.1 on 2024-03-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="leaderboard",),
    ]
