# Generated by Django 4.1 on 2024-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersinformation", "0002_playerprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
