# Generated by Django 5.0.2 on 2024-02-24 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="leaderboard1",
        ),
    ]
