# Generated by Django 4.1 on 2024-03-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievement", "0003_achievement_unlock_score_alter_achievement_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="achievement/static/achievement/images/",
            ),
        ),
    ]
