# Generated by Django 5.0.2 on 2024-02-26 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0002_rename_age_player_point_remove_player_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_id", models.CharField(max_length=255)),
                ("score", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activityboard.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("series_id", "player")},
            },
        ),
    ]
