# Generated by Django 5.0.2 on 2024-02-26 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0003_quizsession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="activityquiz",
        ),
    ]
