# Generated by Django 5.0.2 on 2024-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0004_delete_activityquiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="player",
            field=models.CharField(max_length=155),
        ),
    ]
