# Generated by Django 5.0.2 on 2024-02-27 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0005_alter_quizsession_player"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizsession",
            unique_together=set(),
        ),
    ]
