# Generated by Django 5.0.2 on 2024-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0007_delete_player_remove_quizsession_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="series_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
