# Generated by Django 5.1.dev20240127105402 on 2024-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='series_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
