# Generated by Django 4.1 on 2024-02-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_user_player_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
