# Generated by Django 5.0.2 on 2024-02-25 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activityboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="age",
            new_name="point",
        ),
        migrations.RemoveField(
            model_name="player",
            name="bio",
        ),
    ]
